baseURL = "https://www.mariosanchez.org/"
languageCode = "en-us"
title = "Mario Sanchez Carrion | Personal Site"
[params]
  description = "Mario Sanchez Carrion's Personal Site"
  images = ["https://www.mariosanchez.org/img/msc.jpg"]

